name: asciidoctor-ghpages
on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    
jobs:
  build-upstream:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: asciidoctor-ghpages-upstream
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        asciidoctor_params: --attribute=nofooter -D upstream
  build-downstream:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: asciidoctor-ghpages-downstream
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        asciidoctor_params: --attribute=nofooter

